version: '3.8'

services:
  server:
    build: ./pchess
    command: python app.py -run h 0.0.0.0
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - redis
      - db
    env_file:
      - ./.env.dev

  # celery stuff!
  worker:
    build:
      context: ./pchess
      dockerfile: Dockerfile
    command: celery -A pchess.celery worker -P eventlet
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - .:/code
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
